variables:
  GRADLE_JAVA_IMAGE: gradle:jdk21-alpine
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:25-dind
    alias: docker
    command: ["--tls=false"]



stages:
  - build
  - test
  - imageBuild

build-job:
  stage: build
  image: $GRADLE_JAVA_IMAGE
  script:
    - ./gradlew clean assemble
  rules:
    - if: $CI_COMMIT_BRANCH #run op eender welke branch als er gecommit wordt
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image-build-job:
  stage: imageBuild
  image: $GRADLE_JAVA_IMAGE
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - apk add docker-cli
    - docker version || echo "Docker is not installed correctly"
    - java -version || echo "Java is not installed"
    - which java || echo "Java not in PATH"
    - ./gradlew bootBuildImage
    - docker images
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY/kdg-ti/integratieproject-2/2024-2025/team12/back-end
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test-job:
  stage: test
  image: $GRADLE_JAVA_IMAGE
  script:
    - ./gradlew clean test
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - build/test-results/test/