variables:
  GRADLE_JAVA_IMAGE: gradle:jdk21-alpine

stages:
  - build
  - test

build-job:
  stage: build
  image: $GRADLE_JAVA_IMAGE
  script:
    - ./gradlew clean assemble
  rules:
    - if: $CI_COMMIT_BRANCH #run op eender welke branch als er gecommit wordt
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test-job:
  stage: test
  image: $GRADLE_JAVA_IMAGE
  script:
    - ./gradlew clean test --info
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - build/test-results/test/