### Get access token with normal user
POST http://localhost:8180/realms/Rummikub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=RummikubApp&username=test&password=test&grant_type=password&scope=openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}

### Test: Get Tiles by Player ID (Player 1)
GET http://localhost:8080/api/game/tiles/player/00000000-0000-0000-0000-000000000014
Accept: application/json
Authorization: Bearer {{access_token}}

### Test: Get Tiles by Player ID (Player 2)
GET http://localhost:8080/api/game/tiles/player/00000000-0000-0000-0000-000000000015
Accept: application/json
Authorization: Bearer {{access_token}}

### Test: Get Players by Game ID
GET http://localhost:8080/api/game/players/00000000-0000-0000-0000-000000000011
Accept: application/json
Authorization: Bearer {{access_token}}

### POST game starten met lobbyId, roundTime en startTileAmount en hostUserId -> lobby moet op "ready" staan
POST http://localhost:8080/api/game/start/ef673b41-d76d-4b96-99d8-41beef0c3707
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "turnTime": 60,
  "startTileAmount": 14,
  "hostUserId": "d61e872f-7784-4e27-996b-cad743916105"
}

### call om de zet te cheken op basis van heel de playingfield
GET http://localhost:8080/api/game/turn
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "gameId": "29066fbc-7589-43a7-a85a-da4b02022b01",
  "playerId": "7d9a32c4-a73e-42cc-a7a7-5408cf89f903",
  "tileSets": [
    {
      "tileSetId": "00000000-0000-0000-0000-000000000002",
      "startCoordinate": 1,
      "endCoordinate": 3,
      "tiles": [
        {
          "tileId": "00000000-0000-0000-0000-000000000004",
          "numberValue": 1,
          "color": "BLUE",
          "gridColumn": 4,
          "gridRow": 5
        },
        {
          "tileId": "00000000-0000-0000-0000-000000000007",
          "numberValue": 4,
          "color": "ORANGE",
          "gridColumn": 7,
          "gridRow": 10
        }
      ]
    },
    {
      "tileSetId": "00000000-0000-0000-0000-000000000003",
      "startCoordinate": 11,
      "endCoordinate": 13,
      "tiles": [
        {
          "tileId": "00000000-0000-0000-0000-000000000006",
          "numberValue": 3,
          "color": "BLACK",
          "gridColumn": 7,
          "gridRow": 8
        },
        {
          "tileId": "00000000-0000-0000-0000-000000000005",
          "numberValue": 2,
          "color": "RED",
          "gridColumn": 4,
          "gridRow": 6
        }
      ]
    }
  ],
  "playerDeckDto": {
    "tilesInDeck": [
      {
        "tileId": "00000000-0000-0000-0000-000000000055",
        "numberValue": 5,
        "color": "BLUE",
        "gridColumn": 0,
        "gridRow": 0
      }
    ]
  }
}


#### GET player turn in game player create tileset move
#GET http://localhost:8080/api/game/turn
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "playerId": "917572bc-e704-4202-afea-d94478daf9c4",
#  "gameId": "b9e766b7-16b6-4fc6-a80c-cbf6dad75fb3",
#  "moveType": "CREATE_TILESET",
#  "startCoordinate": 5,
#  "endCoordinate": 11,
#  "tileIds": ["00000000-0000-0000-0000-000000000004"],
#  "playingFieldId": "00000000-0000-0000-0000-000000000001"
#}
#
#GET player turn in game player add tile to tileset move
#GET http://localhost:8080/api/game/turn
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "playerId": "917572bc-e704-4202-afea-d94478daf9c4",
#  "gameId": "b9e766b7-16b6-4fc6-a80c-cbf6dad75fb3",
#  "moveType": "ADD_TILE_TO_TILESET",
#  "tileSet": "00000000-0000-0000-0000-000000000002",
#  "tileIds": ["00000000-0000-0000-0000-000000000006"],
#  "playingFieldId": "00000000-0000-0000-0000-000000000001"
#}

