services:
  postgres_rummikub_db:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_DB: 'rummikub_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '54326:5432'
    networks:
      - backend
    volumes:
      - ./rummikub/postgres/data:/var/lib/postgresql/data

  rummikub_idp_postgres:
    image: postgres:15.8-alpine
    volumes:
      - ./rummikub/idp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - kc

  rummikub_idp_keycloak:
      image: quay.io/keycloak/keycloak:25.0.5
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=Rummikub123
        - KC_DB=postgres
        - KC_DB_URL_HOST=rummikub_idp_postgres
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
      command: start-dev
      ports:
        - "8180:8080"
      depends_on:
        - rummikub_idp_postgres
      networks:
        - kc

networks:
  kc:
    name: kc-network
    driver: bridge
  backend:
    name: back-network
    driver: bridge

